# Understanding Numpy

In [4]:
# import all necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)


NumPy version: 2.3.2


### Creating Numpy Arrays

In [10]:
# Creating arrays from python lists
# 1D array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

#3D array: Like a stack of 2D arrays - useful for images, time series etc
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:", arr2d)
print("3D array: \n", arr3d)


1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]
3D array: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Creating Special Arrays in Numpy

In [ ]:
# Creating arrays filled with zeroes - useful for initializing arrays
#Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

# Creating arrays filled with ones - often used a sstarting points
ones = np.ones((2, 3, 4))       #3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeroes/ones but contain random values
#use when you'll immediately fill the array with real data
empty = np.empty((2, 2))

print("Zeroes array (3x4): \n", zeros)
print("Ones array shape:", ones)
print("Empty array (contains random values): \n", empty)


Zeroes array (3x4): 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Empty array (contains random values): 
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


##### Range arrays

In [19]:
# Range arrays - like python's range () but more powerful
range_arr = np.arange(0, 10, 2) #start, stop, step: [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points including endpoints
linespace_arr = np.linspace(0, 3, 5)
print("Linespace array:", linespace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linespace array: [0.   0.75 1.5  2.25 3.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [23]:
# Identity matrix - diagonal of ones and zeroes elsewhere
# Essential for linear algebra operations
identity = np.eye(4)        #4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4])

# Array filled with a specific value
full_arr = np.full((3, 3), 7)       #3x3 array filled with 7

print("Identity matrix: \n", identity)
print("Diagonal matrix: \n", diagonal)
print("Full array (Filled with 7): \n", full_arr)

Identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix: 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (Filled with 7): 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


### Numpy Data Types (dtypes)

In [30]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)               #32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64)           # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool)     # Boolean  values

# Type conversion - change dtype of existing array
converted = int_arr.astype(np.float32)          #Convert to 32-bit

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"Float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
Float64 uses 8 bytes per element


### Array Properties and Attributes

In [37]:
# Create a sample 3D array for demonstration
# Think of this as 3 layers, each with 4 rows and 5 columns
arr = np.random.randn(3, 4, 5)

# Shape: The dimensions of the array (layers, rows, columns)
print("Shape:", arr.shape)

# Size: Total number of elements (3 x 4 x 5 = 60)
print("Size:", arr.size)

# Ndim: Number of dimensions (3D in this case)
print("Ndim:", arr.ndim)

# Dtype: Data type of elements
print("Dtype:", arr.dtype)  #Usually float 64 for random numbers

# Itemsize: Memory size of each element in bytes
print("Itemsize:", arr.itemsize)        # 8 bytes for float 64

# Total memory usage in bytes
print("memory usage:", arr.nbytes, "bytes")     # size x itemsize
print("memory usage:", arr.nbytes / 1024, "KB") #Convert to KB

Shape: (3, 4, 5)
Size: 60
Ndim: 3
Dtype: float64
Itemsize: 8
memory usage: 480 bytes
memory usage: 0.46875 KB


### Array Indexing & Slicing

In [39]:
# 1D array indexing - similar to python lists
arr1d = np.array([10, 20, 30, 40, 50])

print("first element:", arr1d[0])           # Index 0: 10
print("last element:", arr1d[-1])           # Negative indexing: 50
print("slice [1:4]:", arr1d[1:4])           # Elements 1, 2, 3: [20, 30, 40]
print("Every 2nd element:", arr1d[::2])     # Step of 2: [10, 30, 50]


first element: 10
last element: 50
slice [1:4]: [20 30 40]
Every 2nd element: [10 30 50]


In [43]:
# 2D array indexing = row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access specific element: [row, column]
print("Element at row 1, colums 2:", arr2d[1, 2])       # 7

# Access entire rows or columns
print("First row:", arr2d[0, :])        # All columns fo row 0
print("Second column:", arr2d[:, 1])    # All rows of column 1

# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n", arr2d[1:3, 1:3])

Element at row 1, colums 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


### Advanced Indexing - Powerful selection methods

In [45]:
# Fancy indexing - use arrays of indices to select elements
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4]) # Select elements at positions 0, 2, 4
print("Fancy indexing:", arr[indices])

# This is much more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1]) #   Can repeat and reorder
print("Random order:", arr[random_indices]) # [50, 20, 40, 20]

Fancy indexing: [10 30 50]
Random order: [50 20 40 20]


In [ ]:
# 2D fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3, 4)  # 3x4 array: [[0,1,2,3], [4,5,6,7], [8,9,10,11]]
print("Original 2D array:\n", arr2d)

# Select elements at (row, col) pairs: (0,1) and (2,3)
rows = np.array([0, 2])
cols = np.array([1, 3])
print("Elements at (0,1) and (2,3):", arr2d[rows, cols])  # [1, 11]

# Select entire rows using fancy indexing
selected_rows = arr2d[[0, 2], :]  # Rows 0 and 2, all columns
print("Selected rows:\n", selected_rows)